name: dartevel_logger
version: 0.0.0
description: multi driver logger library for dartevel framework
repository: https://github.com/dartevel/framework

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ">=1.15.0 <2.0.0"
